# Generated by Django 2.2.7 on 2019-11-27 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheerItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=10000)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('date_purchased', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
