# Generated by Django 2.2.5 on 2019-09-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_post_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.CharField(default=1, max_length=1000, verbose_name='<django.db.models.fields.related.ForeignKey><django.db.models.fields.DateTimeField>'),
            preserve_default=False,
        ),
    ]
