# Generated by Django 2.2.5 on 2019-09-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190929_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
