# Generated by Django 2.2.5 on 2019-09-30 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190930_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete='', related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
