# Generated by Django 2.2.5 on 2019-10-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190930_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_tag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
