# Generated by Django 2.2.5 on 2019-10-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_post_category_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_tag',
        ),
    ]
