# Generated by Django 2.2.5 on 2019-10-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='category_tag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
