# Generated by Django 2.2.5 on 2019-10-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_category_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='category_tag',
        ),
    ]
