# Generated by Django 2.2.5 on 2019-10-14 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_remove_userprofile_category_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteeringLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=250)),
                ('activity', models.CharField(max_length=1000)),
                ('hours', models.CharField(max_length=250)),
                ('date_activity', models.CharField(max_length=250)),
                ('supervisor_contact', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
