# Generated by Django 2.2.7 on 2019-11-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_volunteeringlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeringlog',
            name='signature',
            field=models.CharField(default=1, max_length=50000),
            preserve_default=False,
        ),
    ]
