# Generated by Django 2.2.7 on 2019-11-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_volunteeringlog_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
