# Generated by Django 2.2.7 on 2019-11-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191115_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='student_id',
            field=models.IntegerField(default=0),
        ),
    ]
