# Generated by Django 2.2.7 on 2019-11-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191115_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='student_id',
        ),
    ]
