# Generated by Django 2.2.7 on 2019-11-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_userprofile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='clubs',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
