# Generated by Django 2.2.7 on 2019-11-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_clubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='clubs',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
