# Generated by Django 2.2.7 on 2019-11-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191118_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='clubs',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
