# Generated by Django 2.2.7 on 2019-11-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20191118_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='clubs',
            field=models.CharField(blank=True, default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
