# Generated by Django 2.2.7 on 2019-12-01 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191127_0302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VolunteeringLog',
        ),
    ]
